"""Reference-inspired visual system for the desktop search application."""

THEME = {
    "window_bg": "#f3f4f6",
    "surface": "#ffffff",
    "surface_alt": "#f7f8fa",
    "surface_subtle": "#eef1f4",
    "table_bg": "#ffffff",
    "table_header": "#f3f5f7",
    "border": "#d5d9de",
    "border_soft": "#e7eaee",
    "border_strong": "#b9c0c8",
    "text": "#111318",
    "text_secondary": "#343941",
    "text_muted": "#707780",
    "accent": "#2563eb",
    "accent_hover": "#1d4ed8",
    "accent_soft": "#e8f0ff",
    "selection": "#edf4ff",
    "selection_strong": "#dceaff",
    "success": "#2f6f4e",
    "warning": "#8a651e",
    "danger": "#9b3d46",
    "model_bands": ("#ffffff", "#fbfcfd", "#ffffff", "#fafbfc", "#ffffff"),
    "period_separator": "#d9e1ea",
    "model_separator": "#c7d1dc",
    "separator_line": "#e3e8ee",
    "model_separator_line": "#d2dae3",
    "button_bg": "#ffffff",
    "button_hover": "#f1f5f9",
    "button_pressed": "#e7edf4",
    "button_border": "#cbd1d8",
    "button_text": "#111318",
    "button_accent_text": "#1d4ed8",
    "button_disabled": "#e5e7eb",
    "space_xs": 3,
    "space_sm": 6,
    "space_md": 10,
    "space_lg": 14,
    "space_xl": 18,
    "button_pad_x": 10,
    "button_pad_y": 5,
    "primary_pad_x": 13,
    "primary_pad_y": 6,
    "table_row_height": 34,
    "table_header_height": 30,
    "result_gap": 2,
    "period_gap": 5,
    "model_gap": 10,
}

FONT_FAMILY = "SimHei"
FONT_BODY = (FONT_FAMILY, 10)
FONT_LABEL = (FONT_FAMILY, 11)
FONT_TITLE = (FONT_FAMILY, 11, "bold")
FONT_SEARCH = (FONT_FAMILY, 14)
